// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: auth/auth.proto

package auth

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuthServiceRoutes_SignUpAdmin_FullMethodName = "/auth.AuthServiceRoutes/SignUpAdmin"
)

// AuthServiceRoutesClient is the client API for AuthServiceRoutes service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthServiceRoutesClient interface {
	SignUpAdmin(ctx context.Context, in *SignUpRequest, opts ...grpc.CallOption) (*SignUpResponse, error)
}

type authServiceRoutesClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthServiceRoutesClient(cc grpc.ClientConnInterface) AuthServiceRoutesClient {
	return &authServiceRoutesClient{cc}
}

func (c *authServiceRoutesClient) SignUpAdmin(ctx context.Context, in *SignUpRequest, opts ...grpc.CallOption) (*SignUpResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignUpResponse)
	err := c.cc.Invoke(ctx, AuthServiceRoutes_SignUpAdmin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceRoutesServer is the server API for AuthServiceRoutes service.
// All implementations must embed UnimplementedAuthServiceRoutesServer
// for forward compatibility.
type AuthServiceRoutesServer interface {
	SignUpAdmin(context.Context, *SignUpRequest) (*SignUpResponse, error)
	mustEmbedUnimplementedAuthServiceRoutesServer()
}

// UnimplementedAuthServiceRoutesServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthServiceRoutesServer struct{}

func (UnimplementedAuthServiceRoutesServer) SignUpAdmin(context.Context, *SignUpRequest) (*SignUpResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignUpAdmin not implemented")
}
func (UnimplementedAuthServiceRoutesServer) mustEmbedUnimplementedAuthServiceRoutesServer() {}
func (UnimplementedAuthServiceRoutesServer) testEmbeddedByValue()                           {}

// UnsafeAuthServiceRoutesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthServiceRoutesServer will
// result in compilation errors.
type UnsafeAuthServiceRoutesServer interface {
	mustEmbedUnimplementedAuthServiceRoutesServer()
}

func RegisterAuthServiceRoutesServer(s grpc.ServiceRegistrar, srv AuthServiceRoutesServer) {
	// If the following call pancis, it indicates UnimplementedAuthServiceRoutesServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthServiceRoutes_ServiceDesc, srv)
}

func _AuthServiceRoutes_SignUpAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignUpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceRoutesServer).SignUpAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthServiceRoutes_SignUpAdmin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceRoutesServer).SignUpAdmin(ctx, req.(*SignUpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthServiceRoutes_ServiceDesc is the grpc.ServiceDesc for AuthServiceRoutes service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthServiceRoutes_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth.AuthServiceRoutes",
	HandlerType: (*AuthServiceRoutesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SignUpAdmin",
			Handler:    _AuthServiceRoutes_SignUpAdmin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth/auth.proto",
}
