version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: 'orias'
      POSTGRES_PASSWORD: 'orias'
      POSTGRES_DB: 'db_orias'
    ports:
      - "5432:5432"
    networks:
      - container_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  grpc:
    container_name: grpc
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: 2701
      DATABASE_URL: postgresql://orias:orias@postgres:5432/db_orias?sslmode=disable
      SALT_KEY: 12
      JWT_SECRET_KEY: Orimi_027@
      AES_SECRET_KEY: "INDONESIAORIAS27"
      GOOGLE_AUTH_CLIENT_ID: 1028992494328-p8joiknfk0otg90ivl8s5s057kdse2gg.apps.googleusercontent.com
      GOOGLE_AUTH_CLIENT_SECRET: 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
      GOOGLE_AUTH_REDIRECT_URL: http://grpc:2701/api/v1/google_auth/callback
      GOOGLE_OAUTH_STATE_STRING: Orias_271@
      GMAIL_EMAIL: oriastan999@gmail.com
      GMAIL_PASSWORD: qjcylukvwpqibepr
      EMAIL_VERIFICATION_LINK: http://grpc:2701/api/v1/auth/verify-email
      EMAIL_FORGET_PASSWORD_FRONTEND_LINK: http://localhost:3000/forget-password
    networks:
      - container_network
    ports:
      - "2701:2701"
    depends_on:
      - postgres
    
networks:
  container_network:
    name: container_network
    driver: bridge

volumes:
  postgres_data: